version: '3.8'

services:
  pixelzx-node:
    image: yuchanshin/pixelzx-evm:latest
    container_name: pixelzx-mainnet
    restart: unless-stopped
    platform: ${DOCKER_DEFAULT_PLATFORM:-linux/amd64}
    ports:
      - "8545:8545"   # JSON-RPC port
      - "8546:8546"   # WebSocket port
      - "30303:30303" # P2P port
    volumes:
      - ./data:/app/data
      - ./keystore:/app/keystore
      - ./logs:/app/logs
    environment:
      - PIXELZX_CHAIN_ID=8888
      - PIXELZX_NETWORK=mainnet
      - PIXELZX_HOME=/app
      - PIXELZX_CONFIG=/app/config.yaml
      - PIXELZX_DATA_DIR=/app/data
      - PIXELZX_PLATFORM=${DOCKER_DEFAULT_PLATFORM:-linux/amd64}
    command: ["/usr/local/bin/pixelzx", "start", "--config", "/app/data/config.yaml", "--datadir", "/app/data"]
    logging:
      driver: "json-file"
      options:
        max-size: "100m"
        max-file: "5"
    healthcheck:
      test: ["CMD", "/usr/local/bin/pixelzx", "version"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 30s
    networks:
      - pixelzx-network

  # Optional: Add monitoring services
  prometheus:
    image: prom/prometheus:latest
    container_name: pixelzx-prometheus
    ports:
      - "9090:9090"
    volumes:
      - ./monitoring/prometheus.yml:/etc/prometheus/prometheus.yml
      - prometheus-data:/prometheus
    command:
      - '--config.file=/etc/prometheus/prometheus.yml'
      - '--storage.tsdb.path=/prometheus'
      - '--web.console.libraries=/etc/prometheus/console_libraries'
      - '--web.console.templates=/etc/prometheus/consoles'
      - '--storage.tsdb.retention.time=200h'
      - '--web.enable-lifecycle'
    restart: unless-stopped
    networks:
      - pixelzx-network
    profiles:
      - monitoring

  grafana:
    image: grafana/grafana:latest
    container_name: pixelzx-grafana
    ports:
      - "3000:3000"
    volumes:
      - grafana-data:/var/lib/grafana
      - ./monitoring/grafana/provisioning:/etc/grafana/provisioning
    environment:
      - GF_SECURITY_ADMIN_USER=admin
      - GF_SECURITY_ADMIN_PASSWORD=pixelzx-admin
      - GF_USERS_ALLOW_SIGN_UP=false
    restart: unless-stopped
    networks:
      - pixelzx-network
    profiles:
      - monitoring

volumes:
  prometheus-data:
    driver: local
  grafana-data:
    driver: local

networks:
  pixelzx-network:
    driver: bridge
    ipam:
      config:
        - subnet: 172.21.0.0/16