version: '3.8'

services:
  pixelzx-node-1:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: pixelzx-node-1
    ports:
      - "8545:8545"
      - "8546:8546"
      - "30303:30303"
    volumes:
      - ./data/node1:/app/data
    command: ["pixelzx", "start", "--validator"]

  pixelzx-node-2:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: pixelzx-node-2
    ports:
      - "8547:8545"
      - "8548:8546"
      - "30304:30303"
    volumes:
      - ./data/node2:/app/data
    command: ["pixelzx", "start"]

volumes:
  node1-data:
  node2-data: