# PIXELZX POS EVM Chain Production Configuration

# Network Configuration
network:
  name: "pixelzx-mainnet"
  chain_id: 8888
  block_time: 3s
  epoch_length: 200

# Node Configuration
node:
  name: "pixelzx-production-node"
  datadir: "/app/data"
  log_level: "info"

# P2P Network
p2p:
  port: 30303
  max_peers: 100
  bootnode_addrs: []
  enable_upnp: false
  nat: "none"

# JSON-RPC API
rpc:
  enabled: true
  host: "0.0.0.0"
  port: 8545
  cors_origins: ["*"]
  apis: ["eth", "net", "web3", "pxz"]
  gas_cap: 50000000
  tx_fee_cap: 1000000000000000000

# WebSocket API
websocket:
  enabled: true
  host: "0.0.0.0"
  port: 8546
  origins: ["*"]
  apis: ["eth", "net", "web3", "pxz"]

# Validator Configuration
validator:
  enabled: false
  address: ""
  password_file: ""

# Staking Configuration
staking:
  min_validator_stake: "1000000000000000000000000000"  # 1,000,000,000 PXZ (10억 PXZ)
  min_delegator_stake: "10000000000000000000000"       # 10,000 PXZ
  unbonding_period: "504h"                             # 21 days
  max_validators: 125

# Gas Configuration
gas:
  limit: 30000000
  price: 20000000000
  min_price: 1000000000
  price_bump: 10

# Security
security:
  keystore_dir: "/app/keystore"
  auto_unlock: false

# Metrics
metrics:
  enabled: true
  host: "0.0.0.0"
  port: 6060
  expensive: false

# Database
database:
  type: "leveldb"
  cache: 1024
  handles: 512
  ancient: "/app/data/ancient"
  freeze_threshold: 30000000

# Logging
logging:
  level: "info"
  file: "/app/logs/pixelzx.log"
  max_size: "100M"
  max_backups: 10
  max_age: 30
  compress: true

# Performance
performance:
  cache:
    database: 512
    trie: 256
    gc: 25
  workers: 4
  
# Sync Configuration
sync:
  mode: "full"
  gc_mode: "full"
  snapshot: true
  preimages: false

# Transaction Pool
txpool:
  locals: []
  no_locals: false
  journal: "/app/data/transactions.rlp"
  rejournal: "1h"
  price_limit: 1000000000
  price_bump: 10
  account_slots: 16
  global_slots: 4096
  account_queue: 64
  global_queue: 1024
  lifetime: "3h"

# Network Security
network_security:
  trusted_nodes: []
  banned_ips: []
  rate_limit: 1000